<?php
include 'head.php';
    // php update data in mysql database using PDO
    session_start();
    $host = "localhost";
    $username = "root";
    $password = "123456";
    $database = "camagru";
    $message = "";
    
    
    if(isset($_POST['submit']))
    {
        try{
            $connect = new PDO("mysql:host=$host; dbname=$database", $username, $password);
            $connect->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        } 
        catch (PDOException $exc) {
            echo $exc->getMessage();
            exit();
        }
    
        $password = rand(1000, 9999);
        $email = $_POST['email'];
        

    $query = "UPDATE `users` SET `password`=:password WHERE `email` = :email";
    
    $pdoResult = $connect->prepare($query);
    
    $pdoExec = $pdoResult->execute(array(":password"=>hash('whirlpool', $password),":email"=>$email));

    if($pdoResult)
    {
        $str = "your temporary password is -->" .$password;

        mail($email, "CAMAGRU temporary password", $str);
        echo "Check your email for temporary password,you will be redirected in 3 seconds"; 
        header('Refresh: 3; URL=http://localhost:8080/camagru/login.phtml');
    }
    else
    {
        echo 'ERROR Data Not Updated';
    }
    //header('Refresh: 2; URL=http://localhost:8080/camagru/index.php');
}
?>


<!DOCTYPE html>
<html>
    <head>
        <title>UPDATE LOGIN DETAILS</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="css/login.css">
    </head>
    <body>
    <form action="forgotpass.phtml" method="post">
    <h3>Please check your email for a 4-digit temparary password. Sign in as usual using the 4-digit pin
    & then change your password once you are logged in</h3>
    <input class="input" placeholder="Enter email" type="email" name="email" required>
    <input type="submit" name="submit" placeholder="Send mail">
    </form>
    </body>
</html>