<?php include 'login.php';

include 'config/database.php'; ?>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Camagru</title>
    <link rel="stylesheet" type="text/css" href="css/login.css">
</head>
<body>
    <h1>CAMAGRU</h1>
    <div class="box23">
        <div class="box2">
            <h2>LOGIN</h2>
            <form class="form-inline" method="post" action="login.php">
            <h3>Email:</h3>
            <input class="input" placeholder="Enter email" type="text" name="email" required><br>
            <h3>Password:</h3>
            <input class="input" placeholder="Enter password" type="password" name="password" required><br><br>
            <input class="submit" type="submit" value="Submit" name="signin"><br>
            <a href="forgotpass.phtml">Forgot Password?</a>
            </form>
        </div>
        <div class="gaps"></div>
        <div class="box3">
            <h2>SIGN UP</h2>
            <h4>Username:</h4>
        <form class="form-inline" method="post" action="signup.php">
            <input class="input" placeholder="Enter username" type="text" name="username" required><br>
            <h4>Email:</h4>
            <input class="input" placeholder="Enter email address" type="text" name="email" required pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" title="example@example.com"> <br> 
            <h4>Password:</h4>
            <input class="input" placeholder="Enter password" type="password" name="password" required><br><br>
            <a href="home.html"></a><input class="submit" type="submit" name="submit" value="Submit">
        </form>
        </div>
    </div>
</body>
</html>