<?php
include 'head.php';

// php update data in mysql database using PDO
session_start();
$host = "localhost";
$username = "root";
$password = "123456";
$database = "camagru";
$message = "";
echo"SESSION";var_dump($_SESSION);

if(isset($_POST['submit']))
{
    try{
        $connect = new PDO("mysql:host=$host; dbname=$database", $username, $password);
        $connect->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    } catch (PDOException $exc) {
        echo $exc->getMessage();
        exit();
    }

    
//     // get values from input text form and number
   
    $username = $_POST['usernamenew'];
    $emailnew = $_POST['emailnew'];
    $password = hash('whirlpool',$_POST['passwordnew']);
    $email = $_SESSION['email'];

    // if (strlen($pass) < 6 || strlen($pass) > 12 || !preg_match("#[A-Z]+#", $pass))
    //     {
    //         echo ("password must be 6-12 characters and contain atleast 1 capital letter");
    //         header('Refresh: 2; URL=http://localhost:8080/camagru/settings.phtml');
    //     }
    
//     // mysql query to Update data
if (isset($_SESSION['email']))
{ 
    $update = $connect->prepare("UPDATE users SET username='$username', password='$password', email='$emailnew' WHERE email='$email'");
    $update->execute();
    echo "Your changes have been made. You will be redirected";
    header('Refresh: 2; URL=http://localhost:8080/camagru/login.phtml');
}

}


?>

<!DOCTYPE html>
<html>
    <head>
        <title>UPDATE LOGIN DETAILS</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="css/login.css">
    </head>
    <body>
        <form action="settings.phtml" method="post">
        <h3>Enter new username :</h3>
            <input class="input" type="text" name="usernamenew" required placeholder="username"><br><br>
            <h4>Enter new password :</h4>
            <input class="input" type="password" name="passwordnew" required placeholder="password"><br><br>
        <h3>Enter new email :</h3>
        <input class="input" type="text" name="emailnew" required placeholder="email"><br><br>
        <input class="submit" type="submit" name="submit" required placeholder="submit">
        </form>
    </body>
</html>
